In [1]:
import pandas as pd
import numpy as np
import  nltk #natural language tool kit
import re #regular expression -removing the special characters
from  nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [3]:
import pandas as pd
import numpy as np
import  nltk #natural language tool kit
import re #regular expression -removing the special characters
from  nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [54]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
import tensorflow as tf
from tensorflow.keras import backend as k

In [55]:
import pandas as pd
import numpy as np
import  nltk #natural language tool kit
import re #regular expression -removing the special characters
from  nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split


In [56]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [57]:
from tensorflow.keras import models

In [58]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import layers


In [59]:
import pandas as pd
import numpy as np
import  nltk #natural language tool kit
import re #regular expression -removing the special characters
from  nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split

In [60]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [61]:
from tensorflow.keras import layers

In [62]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.

if os.environ.get('RUNTIME_ENV_LOCATION_TYPE') == 'external':
    endpoint_a4b346bcdab7475a847975ee9ac4f09c = 'https://s3.eu.cloud-object-storage.appdomain.cloud'
else:
    endpoint_a4b346bcdab7475a847975ee9ac4f09c = 'https://s3.private.eu.cloud-object-storage.appdomain.cloud'

client_a4b346bcdab7475a847975ee9ac4f09c = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='PZoBc-2q5JdiL5HJxx7eK0BMWF-wqmss_cr2kXAC0OXt',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url=endpoint_a4b346bcdab7475a847975ee9ac4f09c)

body = client_a4b346bcdab7475a847975ee9ac4f09c.get_object(Bucket='amazonkindle-donotdelete-pr-g9plr1qo7td0ze',Key='kindle_reviews update.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_1 = pd.read_csv(body)
df_data_1.head()


id        asin helpful  overall  \
0   0  B000F83SZQ  [0, 0]        5   
1   1  B000F83SZQ  [2, 2]        4   
2   2  B000F83SZQ  [2, 2]        4   
3   3  B000F83SZQ  [1, 1]        5   
4   4  B000F83SZQ  [0, 1]        4   

                                          reviewText   reviewTime  \
0  I enjoy vintage books and movies so I enjoyed ...   05 5, 2014   
1  This book is a reissue of an old one; the auth...   01 6, 2014   
2  This was a fairly interesting read.  It had ol...   04 4, 2014   
3  I'd never read any of the Amy Brewster mysteri...  02 19, 2014   
4  If you like period pieces - clothing, lingo, y...  03 19, 2014   

       reviewerID                         reviewerName             summary  \
0  A1F6404F1VG29J                           Avidreader  Nice vintage story   
1   AN0N05A9LIJEQ                             critters        Different...   
2   A795DMNCJILA6                                  dot               Oldie   
3  A1FV0SX13TWVXQ  Elaine H. Turley "Montana Songbird"  I really liked it.   
4  A3SPTOKDG7WBLN                   Father Dowling Fan      Period Mystery   

   unixReviewTime  
0      1399248000  
1      1388966400  
2      1396569600  
3      1392768000  
4      1395187200

In [63]:
nltk.download("stopwords")
print(list(df_data_1.columns))

['id', 'asin', 'helpful', 'overall', 'reviewText', 'reviewTime', 'reviewerID', 'reviewerName', 'summary', 'unixReviewTime']


[nltk_data] Downloading package stopwords to /home/wsuser/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [64]:
from sklearn.feature_extraction.text import CountVectorizer
df=[]
for i in range(0,1000):
    review=df_data_1['reviewText'][i]
    #a)remove un neccessary .,
    review=re.sub('[^a-zA-Z]',' ',review)
    #b) lower case the text
    review=review.lower()
    #c)split the text
    review=review.split()
    #4.stemming
    #5. remove stop words
    ps=PorterStemmer()
    review=[ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    #6.join the splitted data
    review=' '.join(review)
    df.append(review)

cv=CountVectorizer(max_features=9)

In [65]:
x=cv.fit_transform(df).toarray()
print("Outputting Devi")
print(x)

y=df_data_1.iloc[0:1000:,3:4].values
print(y)

Outputting Devi
[[2 0 1 ... 2 0 0]
 [1 0 1 ... 0 0 1]
 [0 0 0 ... 3 2 0]
 ...
 [3 0 0 ... 1 1 0]
 [0 0 0 ... 1 0 0]
 [3 0 1 ... 1 0 0]]
[[5]
 [4]
 [4]
 [5]
 [4]
 [4]
 [4]
 [4]
 [5]
 [4]
 [5]
 [4]
 [3]
 [3]
 [5]
 [5]
 [5]
 [3]
 [5]
 [4]
 [5]
 [2]
 [5]
 [4]
 [5]
 [3]
 [5]
 [3]
 [4]
 [5]
 [5]
 [5]
 [5]
 [4]
 [3]
 [3]
 [3]
 [5]
 [5]
 [2]
 [3]
 [3]
 [2]
 [5]
 [5]
 [5]
 [5]
 [5]
 [5]
 [5]
 [5]
 [5]
 [4]
 [3]
 [4]
 [4]
 [5]
 [4]
 [4]
 [5]
 [5]
 [4]
 [5]
 [5]
 [1]
 [1]
 [1]
 [1]
 [3]
 [4]
 [2]
 [1]
 [2]
 [1]
 [5]
 [5]
 [1]
 [4]
 [5]
 [1]
 [5]
 [1]
 [5]
 [5]
 [4]
 [4]
 [1]
 [2]
 [4]
 [4]
 [4]
 [4]
 [3]
 [3]
 [4]
 [4]
 [4]
 [3]
 [4]
 [5]
 [1]
 [4]
 [5]
 [4]
 [5]
 [5]
 [1]
 [5]
 [2]
 [4]
 [5]
 [3]
 [5]
 [3]
 [4]
 [5]
 [5]
 [4]
 [4]
 [1]
 [4]
 [5]
 [1]
 [5]
 [5]
 [5]
 [2]
 [3]
 [3]
 [5]
 [3]
 [3]
 [5]
 [5]
 [5]
 [4]
 [4]
 [3]
 [4]
 [3]
 [4]
 [2]
 [3]
 [4]
 [3]
 [4]
 [2]
 [5]
 [5]
 [5]
 [3]
 [5]
 [5]
 [3]
 [5]
 [1]
 [4]
 [5]
 [4]
 [5]
 [5]
 [5]
 [5]
 [2]
 [4]
 [4]
 [2]
 [5]
 [5]
 [5]
 [1]
 [2]
 [5]

In [66]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(800, 9)
(200, 9)
(800, 1)
(200, 1)


In [67]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential, load_model


In [68]:
model = tensorflow.keras.Sequential()
model.add(layers.Dense(input_dim=9, units=1000, kernel_initializer="random_uniform",activation="relu")) # input layer
model.add(layers.Dense(units=9, kernel_initializer="random_uniform", activation="relu")) # 1st hidden layer
model.add(layers.Dense(units= 1, kernel_initializer="random_uniform", activation="sigmoid")) # output layer

In [69]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["acc"])


In [70]:
model.fit(x_train,y_train,batch_size=128,epochs=1)


7/7 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - acc: 0.0375


In [71]:
a="amazo.h5"

In [51]:
pwd

'/home/wsuser/work'

In [72]:
tensorflow.keras.models.save_model(model,a)

In [73]:
!tar -zcvf Amazon_kindlereview.tgz amazo.h5

amazo.h5


In [74]:
ls -1

amazo.h5
Amazon_kindlereview.tgz
amazo.sav


In [75]:
!pip install watson-machine-learning-client --upgrade


In [76]:
!pip install --upgrade "ibm-watson>=5.2.3"


In [77]:
from ibm_watson_machine_learning import APIClient
wml_credentials = { "url": "https://eu-gb.ml.cloud.ibm.com",
                  "apikey": "i5pQI34nS5IUBRknr4pGgnsSe0N3D5SZkVdmGsMTehn4"
                  }

In [78]:
client = APIClient(wml_credentials)

In [80]:
def guide_from_space_name(client,space_name):
    space = client.spaces.get_details()
    return(next(item for item in space['resources']if item['entity']["name"]== space_name)['metadata']['id'])

In [81]:
space_uid = guide_from_space_name(client,'amazon')
print("Space UID = " + space_uid)

Space UID = 2f6b7fd7-b9b8-4de6-b5ad-366222c238ff


In [82]:
client.set.default_space(space_uid)

client.software_specifications.list()

software_spec_uid = client.software_specifications.get_uid_by_name("tensorflow_1.15-py3.6")


-----------------------------  ------------------------------------  ----
NAME                           ASSET_ID                              TYPE
default_py3.6                  0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base
pytorch-onnx_1.3-py3.7-edt     069ea134-3346-5748-b513-49120e15d288  base
scikit-learn_0.20-py3.6        09c5a1d0-9c1e-4473-a344-eb7b665ff687  base
spark-mllib_3.0-scala_2.12     09f4cff0-90a7-5899-b9ed-1ef348aebdee  base
ai-function_0.1-py3.6          0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base
shiny-r3.6                     0e6e79df-875e-4f24-8ae9-62dcc2148306  base
tensorflow_2.4-py3.7-horovod   1092590a-307d-563d-9b62-4eb7d64b3f22  base
pytorch_1.1-py3.6              10ac12d6-6b30-4ccd-8392-3e922c096a92  base
tensorflow_1.15-py3.6-ddl      111e41b3-de2d-5422-a4d6-bf776828c4b7  base
scikit-learn_0.22-py3.6        154010fa-5b3b-4ac1-82af-4d5ee5abbc85  base
default_r3.6                   1b70aec3-ab34-4b87-8aa0-a4a3c8296a36  base
pytorch-onnx_1.3-py3.6         1bc6029

In [83]:
software_spec_uid


'2b73a275-7cbf-420b-a912-eae7f436e0bc'

In [84]:
!pip install watson-machine-learning-client


In [85]:
model_details = client.repository.store_model(model='Amazon_kindlereview.tgz',
                                              meta_props= {
                                                  client.repository.ModelMetaNames.NAME:"NLP",
                                                  client.repository.ModelMetaNames.TYPE:"keras_2.2.4",
                                                  client.repository.ModelMetaNames.SOFTWARE_SPEC_UID:software_spec_uid
                                              }) 
model_id = client.repository.get_model_uid(model_details)

Note: Warnings!! :  Model type keras_2.2.4 is deprecated. We recommend you use a supported model type. See Supported Frameworks https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/pm_service_supported_frameworks.html


In [86]:
model_id

'c58254c9-56d3-4eb6-a23e-589015796f20'

In [87]:
ypred=model.predict(x_test)

In [88]:
ypred

array([[0.5166775 ],
       [0.5158881 ],
       [0.50925297],
       [0.50936717],
       [0.5473905 ],
       [0.51463854],
       [0.5286883 ],
       [0.5228322 ],
       [0.50407994],
       [0.5167508 ],
       [0.5224986 ],
       [0.57762265],
       [0.5314573 ],
       [0.51163524],
       [0.50889987],
       [0.5323045 ],
       [0.54420274],
       [0.5079292 ],
       [0.5131936 ],
       [0.533614  ],
       [0.5153952 ],
       [0.52707535],
       [0.5081451 ],
       [0.5081451 ],
       [0.5232778 ],
       [0.5390204 ],
       [0.51163524],
       [0.50407994],
       [0.5081451 ],
       [0.5234825 ],
       [0.5081451 ],
       [0.51048213],
       [0.51078564],
       [0.5104306 ],
       [0.53368706],
       [0.510936  ],
       [0.53066003],
       [0.510936  ],
       [0.50968134],
       [0.52397245],
       [0.5161711 ],
       [0.52233624],
       [0.5331088 ],
       [0.51417327],
       [0.50407994],
       [0.5247776 ],
       [0.50762784],
       [0.514

In [89]:
model = load_model('amazo.h5')

In [91]:
#save bag of word model
import joblib
joblib.dump(cv.vocabulary_,"amazo.save")

['amazo.save']

In [92]:
loaded=CountVectorizer(decode_error='replace',vocabulary=joblib.load('amazo.save'))

In [96]:
d="Writing was good"
d=d.split('delimiter')
result=model.predict(loaded.transform(d))
print(result)
prediction=result<0.5
#print(prediction)
if prediction[0] == False:
    print("Positive review")
elif prediction[0] == True:
    print("Negative review")

[[0.50762784]]
Positive review
