In [43]:
!pip install jupyterthemes

In [44]:
!jt -t monokai -f fira -fs 13 -nf ptsans -nfs 10 -N -kl -cursw 5 -cursc r -cellw 80% -T

In [45]:
#import required libraries

#import pandas library
import pandas as pd
#import numpy
import numpy as np
#import requests
import requests
#import io
import io

In [46]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [47]:
#import the dataset in the data variable
data=pd.read_csv('/content/drive/MyDrive/ML.VEC/kindle_reviews (1).csv')

In [48]:
data.shape

(982619, 10)

In [49]:
data.head()

Unnamed: 0        asin  ...             summary  unixReviewTime
0           0  B000F83SZQ  ...  Nice vintage story      1399248000
1           1  B000F83SZQ  ...        Different...      1388966400
2           2  B000F83SZQ  ...               Oldie      1396569600
3           3  B000F83SZQ  ...  I really liked it.      1392768000
4           4  B000F83SZQ  ...      Period Mystery      1395187200

[5 rows x 10 columns]

In [50]:
#assigning 50000 rows to data
data=data.head(50000)

In [51]:
#checking for null values
data.isnull().any()

Unnamed: 0        False
asin              False
helpful           False
overall           False
reviewText         True
reviewTime        False
reviewerID        False
reviewerName       True
summary           False
unixReviewTime    False
dtype: bool

In [52]:
data.isnull().sum()

Unnamed: 0          0
asin                0
helpful             0
overall             0
reviewText          1
reviewTime          0
reviewerID          0
reviewerName      149
summary             0
unixReviewTime      0
dtype: int64

In [53]:
#deleting or dropping the unwanted columns from the dataset
del data['Unnamed: 0']
del data['asin']
del data['helpful']
del data['reviewTime']
del data['reviewerID']
del data['reviewerName']
del data['unixReviewTime']

In [54]:
#first 10 rows of data
data.head(10)

overall  ...                                        summary
0        5  ...                             Nice vintage story
1        4  ...                                   Different...
2        4  ...                                          Oldie
3        5  ...                             I really liked it.
4        4  ...                                 Period Mystery
5        4  ...                                         Review
6        4  ...                       Nice old fashioned story
7        4  ...  Enjoyable reading and reminding the old times
8        5  ...                                     Darth Maul
9        4  ...                       Not bad, not exceptional

[10 rows x 3 columns]

In [55]:
#checking value counts
data.overall.value_counts()

5    23090
4    14980
3     7013
2     2832
1     2085
Name: overall, dtype: int64

In [56]:
#check the null values
data.isna().sum()

overall       0
reviewText    1
summary       0
dtype: int64

In [57]:
#joining review description and summary into one col
data['reviewText']=data['reviewText']+" "+data['summary']

In [58]:
data.head()

overall  ...             summary
0        5  ...  Nice vintage story
1        4  ...        Different...
2        4  ...               Oldie
3        5  ...  I really liked it.
4        4  ...      Period Mystery

[5 rows x 3 columns]

In [59]:
data.drop(['summary'],axis=1,inplace=True)

In [60]:
#checking for null values
data.isna().sum()

overall       0
reviewText    1
dtype: int64

In [61]:
#since there is only one null value, replace it with blank space
data['reviewText'].fillna("",inplace = True)

In [62]:
#Grouping the overall rating of scale 1-5 to 2 categories
def review_sentiment(rating):
    #0(positive) and  with 1(negative) 
    if(rating == 5 or rating == 4 or rating==3):
        return 0
    else:
        return 1

In [63]:
data.overall = data.overall.apply(review_sentiment)

In [64]:
data.overall.value_counts()

0    45083
1     4917
Name: overall, dtype: int64

In [65]:
data.head(50)

overall                                         reviewText
0         0  I enjoy vintage books and movies so I enjoyed ...
1         0  This book is a reissue of an old one; the auth...
2         0  This was a fairly interesting read.  It had ol...
3         0  I'd never read any of the Amy Brewster mysteri...
4         0  If you like period pieces - clothing, lingo, y...
5         0  A beautiful in-depth character description mak...
6         0  I enjoyed this one tho I'm not sure why it's c...
7         0  Never heard of Amy Brewster. But I don't need ...
8         0  Darth Maul working under cloak of darkness com...
9         0  This is a short story focused on Darth Maul's ...
10        0  I think I have this one in both book and audio...
11        0  Title has nothing to do with the story.  I did...
12        0  Well written. Interesting to see Sideous (thro...
13        0  Troy Denning's novella Recovery was originally...
14        0  I am not for sure on how much of a difference ...
15        0  I really enjoyed the book. Had the normal back...
16        0  Great read enjoyed every minute of it .  I thi...
17        0  Another well written eBook by Troy Denning, bu...
18        0  This one promises to be another good book. I h...
19        0  I have a version of "Star by Star" that does n...
20        0  Excellent! Very well written story, very excit...
21        1  With Ylesia, a novella originally published in...
22        0  Great book couldn't put it down.  The story ex...
23        0  Most of the New Jedi Order books focus on the ...
24        0  I was hoping to find this one in book form. Th...
25        0  The events of "Ylesia" take place during "Dest...
26        0  Really shouldn't have Han Solo on the cover as...
27        0  Originally published as an e-book coinciding w...
28        0  This book was a good idea. I have always wante...
29        0  Great short story. It gives a little more insi...
30        0  I love anything with Chewbacca in it.  Him and...
31        0  A great little chapter to read on my Kindle, b...
32        0  I love the stories with Chewie in them! this e...
33        0  I'm not really sure where it actually fits int...
34        0  I really do enjoy Troy Denning's work, I want ...
35        0  Timothy Zahn's Fool's Bargain is a short story...
36        0  Not too bad, an intro-short-story for some big...
37        0  I absolutely love this book. Though it is shor...
38        0  What can I say Stormtroopers.  A story with tr...
39        1  For whatever reason, Star Wars short stories a...
40        0  As an ebook it reads very well on my Kindle, b...
41        0  ** Note: this story appears as a bonus in the ...
42        1  I admit it, I snapped this up the moment I saw...
43        0  I love Timothy Zahn's work!  He does what no o...
44        0  The hero in this story has been living in NYC ...
45        0  The Iron Marshall, by Louie L`Amour is one of ...
46        0  This is yet another  L'Amour winner. I have ye...
47        0  I almost didn't get this book because of the c...
48        0  This story by Louis L'Amour was the very first...
49        0  This is how it was in the big gambling and cor...

In [66]:
len(list(data['overall']))

50000

In [67]:
x=data.iloc[:,1].values

In [68]:
#import natural language toolkit
import nltk
#nltk.download("stopwords")
#nltk.download("wordnet")
#import stopwords library to remove stopwords
from nltk.corpus import stopwords
#library used for stem the words
from nltk.stem.porter import PorterStemmer
#create an object for stemming
ps = PorterStemmer()
#library used for stem the words
from nltk.stem import WordNetLemmatizer
#create an object for wordnet lemmatizer
wordnet=WordNetLemmatizer()

In [69]:
import re

In [70]:
import nltk
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [73]:
 # Initialize empty array to append clean text 
corpus=[]
# no of rows to clean 
for i in range(len(x)):
    #replacing punctuations and numbers using re library 
    temp=re.sub('[^a-zA-Z]',' ',x[i])
    # convert all text to lower cases
    temp=temp.lower()
    # split to array(default delimiter is " ") 
    temp=temp.split()
    # creating WordNetLemmatizer object to take main lemma of each word
    wordnet = WordNetLemmatizer()
    #loop for leammatization each word in string array at ith row 
    temp=[wordnet.lemmatize(word) for word in temp if not word in set(
        stopwords.words('english'))]
    #rejoin all string array elements to create back into a string 
    temp=' '.join(temp)
    #append each string to create array of clean text 
    corpus.append(temp)

In [74]:
#creating bag of word model
from sklearn.feature_extraction.text import CountVectorizer
#To extract max feature, "max_features" is attribute to 
#experiment with to get better results
cv=CountVectorizer(max_features= 6000)
#z contains vectorized data (independent variable) 
z=cv.fit_transform(corpus).toarray()

In [ ]:
z.shape

(1, 64)

In [75]:
#save bag of word model
import joblib
joblib.dump(cv.vocabulary_,"amazo.save")

['amazo.save']

In [76]:
y=data.iloc[:,0].values
y

array([0, 0, 0, ..., 0, 0, 0])

In [77]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(z,y,test_size=0.2,random_state=0)

In [78]:
x_train.shape

(40000, 6000)

In [81]:
x_test.shape

(10000, 6000)

In [82]:
z.shape

(50000, 6000)

In [83]:
#import libraries
import tensorflow
import keras
#import Sequential
from tensorflow.keras.models import Sequential
#import Dense
from tensorflow.keras.layers import Dense

In [84]:
#intialize the model
model=Sequential()

#adding input layer
model.add(Dense(600,kernel_initializer='random_uniform',
                activation='relu'))

#adding hidden layer
model.add(Dense(100,kernel_initializer='random_uniform',
                activation='relu'))

#adding output layer
model.add(Dense(1,kernel_initializer='random_uniform',
                activation='sigmoid'))

#configure the learning process
model.compile(optimizer='adam',loss='binary_crossentropy',
              metrics=['accuracy'])

In [85]:
print(x_train)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [86]:
#training the model
model.fit(x_train,y_train,epochs=20,batch_size=32)

Epoch 1/20
1250/1250 [==============================] - 36s 28ms/step - loss: 0.2032 - accuracy: 0.9247
Epoch 2/20
1250/1250 [==============================] - 35s 28ms/step - loss: 0.1132 - accuracy: 0.9557
Epoch 3/20
1250/1250 [==============================] - 35s 28ms/step - loss: 0.0439 - accuracy: 0.9850
Epoch 4/20
1250/1250 [==============================] - 35s 28ms/step - loss: 0.0081 - accuracy: 0.9976
Epoch 5/20
1250/1250 [==============================] - 35s 28ms/step - loss: 0.0013 - accuracy: 0.9998
Epoch 6/20
1250/1250 [==============================] - 35s 28ms/step - loss: 2.0240e-04 - accuracy: 1.0000
Epoch 7/20
1250/1250 [==============================] - 36s 29ms/step - loss: 2.0123e-05 - accuracy: 1.0000
Epoch 8/20
1250/1250 [==============================] - 35s 28ms/step - loss: 5.1649e-06 - accuracy: 1.0000
Epoch 9/20
1250/1250 [==============================] - 36s 29ms/step - loss: 1.7767e-06 - accuracy: 1.0000
Epoch 10/20
1250/1250 [=========================

In [87]:
#save the model
model.save("amazo.h5")

In [88]:
ypred=model.predict(x_test)

In [89]:
ypred

array([[0.0000000e+00],
       [2.8997588e-32],
       [0.0000000e+00],
       ...,
       [0.0000000e+00],
       [0.0000000e+00],
       [1.1353453e-17]], dtype=float32)

In [90]:
#save bag of word model
import joblib
joblib.dump(cv.vocabulary_,"amazo.save")

['amazo.save']

In [91]:
loaded=CountVectorizer(decode_error='replace',vocabulary=joblib.load('amazo.save'))

In [92]:
d="Writing was good"
d=d.split('delimiter')
result=model.predict(loaded.transform(d))
print(result)
prediction=result>0.5
#print(prediction)
if prediction[0] == False:
    print("Positive review")
elif prediction[0] == True:
    print("Negative review")


[[6.6129434e-07]]
Positive review


In [93]:
from tensorflow.keras.models import load_model
model=tensorflow.keras.models.load_model("amazo.h5")

In [94]:
#import load_model function
from tensorflow.keras.models import load_model
#load our saved model file
model=tensorflow.keras.models.load_model("amazo.h5")
#import countvecorizer
from sklearn.feature_extraction.text import CountVectorizer
import joblib
#load saved bag of word model file
loaded=CountVectorizer(decode_error='replace',vocabulary=joblib.load('amazo.save'))

In [95]:
d="good with application"
d=d.split('delimiter')
result=model.predict(loaded.transform(d))
print(result)
prediction=result>0.5
#print(prediction)
if prediction[0] == False:
    print("Positive review")
elif prediction[0] == True:
    print("Negative review")

[[1.1525676e-12]]
Positive review
